// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'9cc5f65adace8a255aa866795ab428a2c127775e589dd38c41f4250a09e8f1fc'>;
export type ExecutionHash =
  ExecutionHashBase<'49613244008792ecc1bc4a5844cb64afd5e36442104aad35cb7089ae0cd2ffcf'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly OAuthAccount: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly provider: CodecTypes['pg/text@1']['output'];
      readonly providerId: CodecTypes['pg/text@1']['output'];
      readonly accessToken: CodecTypes['pg/text@1']['output'] | null;
      readonly refreshToken: CodecTypes['pg/text@1']['output'] | null;
      readonly expiresAt:
        CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
      readonly avatar: CodecTypes['pg/text@1']['output'] | null;
      readonly password: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly role: 'USER' | 'ADMIN';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly OAuthAccount: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly provider: CodecTypes['pg/text@1']['input'];
      readonly providerId: CodecTypes['pg/text@1']['input'];
      readonly accessToken: CodecTypes['pg/text@1']['input'] | null;
      readonly refreshToken: CodecTypes['pg/text@1']['input'] | null;
      readonly expiresAt:
        CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
      readonly avatar: CodecTypes['pg/text@1']['input'] | null;
      readonly password: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly role: 'USER' | 'ADMIN';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly oauth_accounts: {
      readonly access_token: CodecTypes['pg/text@1']['output'] | null;
      readonly expires_at:
        CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly provider: CodecTypes['pg/text@1']['output'];
      readonly provider_id: CodecTypes['pg/text@1']['output'];
      readonly refresh_token: CodecTypes['pg/text@1']['output'] | null;
      readonly user_id: CodecTypes['pg/text@1']['output'];
    };
    readonly users: {
      readonly avatar: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly password: CodecTypes['pg/text@1']['output'] | null;
      readonly role: 'USER' | 'ADMIN';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly oauth_accounts: {
      readonly access_token: CodecTypes['pg/text@1']['input'] | null;
      readonly expires_at:
        CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly provider: CodecTypes['pg/text@1']['input'];
      readonly provider_id: CodecTypes['pg/text@1']['input'];
      readonly refresh_token: CodecTypes['pg/text@1']['input'] | null;
      readonly user_id: CodecTypes['pg/text@1']['input'];
    };
    readonly users: {
      readonly avatar: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly password: CodecTypes['pg/text@1']['input'] | null;
      readonly role: 'USER' | 'ADMIN';
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly oauth_accounts: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly provider: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly provider_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly access_token: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly refresh_token: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly expires_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['provider', 'provider_id'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'oauth_accounts_user_id_idx_6c952402';
                  readonly prefix: 'oauth_accounts_user_id_idx';
                  readonly columns: readonly ['user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'oauth_accounts';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly avatar: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'USER'>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['username'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['USER', 'ADMIN'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'User';
    };
    readonly oauth_accounts: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'OAuthAccount';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly OAuthAccount: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly provider: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly providerId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly accessToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly refreshToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly expiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'oauth_accounts';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly provider: { readonly column: 'provider' };
                readonly providerId: { readonly column: 'provider_id' };
                readonly accessToken: { readonly column: 'access_token' };
                readonly refreshToken: { readonly column: 'refresh_token' };
                readonly expiresAt: { readonly column: 'expires_at' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly avatar: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly password: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly accounts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OAuthAccount';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly username: { readonly column: 'username' };
                readonly avatar: { readonly column: 'avatar' };
                readonly password: { readonly column: 'password' };
                readonly name: { readonly column: 'name' };
                readonly role: { readonly column: 'role' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
        };
        readonly enum: {
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'USER'; readonly value: 'USER' },
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'oauth_accounts';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'users';
            readonly column: 'id';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'uuidv4';
          };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'users';
            readonly column: 'updated_at';
          };
          readonly onCreate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
          readonly onUpdate: {
            readonly kind: 'generator';
            readonly id: 'timestampNow';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
